<?php
/**
 * json.php - 14 jan. 2011
 * 
 * Fichier de vue : json
 * Renvoie les données de la vue au format json
 * 
 * PHP Version 5
 * 
 * @category  View
 * @package   Root
 * @author    Matthieu Bacconnier <matthieu@bacconnier.fr>
 * @copyright 2011 Matthieu Bacconnier
 * @license   Copyright http://fr.wikipedia.org/wiki/Copyright
 * @link      http://edevoir.com
 * @see       AbstractController::json
 * @see       AbstractController::ajax
 */
echo json_encode($this->jsonDatas);
?>