<?php 
$Module = $this->getController()->getModule();

if($Module != 'administrateur')
{
	echo $this->Doc_box($this->getController()->getModule(), 'faq', 'Besoin d\'aide sur cette page ?');
}

$AddReply = '<p class="faq-ajout-reponse"><a href="#" data-question-id="__data__">Ajouter une réponse</a></p>';
?>

<h2 id="membre-exercice-faq-chat">Chat actuel</h2>
<p style="display: none;" class="important" id="faq-nouveaux">De nouveaux éléments ont été ajoutés ! <a href="">Cliquez pour mettre à jour la page</a>.</p>

<div class="texable">
<?php 
if(empty($this->FAQ))
{
	?>
	<p>Aucune question n'a été posée sur cet exercice.</p>
	<?php 
}
else
{
	$LastQuestion = null;
	foreach($this->FAQ as $ID => $Datas)
	{
		if(empty($Datas['Parent']))
		{
			//Lien ajout réponse
			if(!is_null($LastQuestion))
			{
				//Lien d'ajout de réponse à la question
				echo str_replace('__data__', $LastQuestion, $AddReply);
			}
			
			//QUESTION
			?>
			<h3 class="faq-question faq-<?php echo $Datas['Type'] ?>"><?php echo nl2br($Datas['Texte']) ?></h3>
			<?php
			$LastQuestion = $ID;
		}
		else
		{
			//RÉPONSE
			?>
			<p class="faq-reponse faq-<?php echo $Datas['Type'] ?>"><?php echo nl2br($Datas['Texte']) ?></p>		
			<?php
		}
	}
	
	if(!is_null($LastQuestion))
	{
		//Lien d'ajout de réponse à la question
		echo str_replace('__data__', $LastQuestion, $AddReply);
	}
}
?>
</div>

<?php
if($this->Ouvert)
{
	?>

	<h2 id="membre-exercice-faq-question">Poster une nouvelle question</h2>
	<form id="form_faq-question-exercice" method="post" action="">
	<?php 
	echo $this->Form_textareaLabeLBr(
		'question',
		'Votre question',
		array(
			'required' => 'required',
			'class' => 'tex-container'
		)
	);
	
	echo $this->Form_submit('faq-question-exercice', 'Envoyer cette question');
	?>
	</form>

	<?php 
}//Fin if($this->Ouvert)
?>