<?php
if(isset($this->Infos))
{
	echo '<p class="infos">' . $this->Infos . '</p>';
}
?>

<div class="fichiers">
<?php
$Images = array('jpg', 'jpeg', 'png', 'gif');
$Documents = array('pdf', 'doc', 'docx', 'odt');

echo $this->Exercice_infos($this->Exercice, $this->Type);

foreach($this->Fichiers as $URL => $Infos)
{
	$LongURL = URL . '/public/exercices/' . $this->Exercice->LongHash . $URL;
	echo '<p class="fichier"><a href="' . $LongURL . '">' . $Infos['NomUpload'] . '</a><br />' . PHP_EOL;
	
	$Extension = Util::extension($URL);
	if(in_array($Extension, $Images))
	{
		echo '<a href="/public/exercices/' . $this->Exercice->LongHash . $URL . '" rel="prettyphoto[fichiers]"><img src="/public/exercices/' . $this->Exercice->LongHash . $URL . '" alt="' . $this->Exercice->Titre . ', fichier ' . $Infos['NomUpload'] . '" class="fichier-sujet" /></a>';
	}
	elseif(in_array($Extension, $Documents))
	{
		echo '<iframe src="http://docs.google.com/viewer?url=' . urlencode($LongURL) . '&amp;embedded=true" style="border: none; width:96%; height:780px; margin-left:2%;"></iframe>';
	}
	else
	{
		echo '<a href="' . $URL . '">Télécharger</a>.';
	}
	echo "\n</p>";
}
?>
</div>