<?php 
//Créer dans un fichier temporaire
$ZipURL = tempnam(sys_get_temp_dir(), $this->Exercice->Hash . '.zip');


$zip = new ZipArchive();
$zip->open($ZipURL, ZIPARCHIVE::CREATE);

//Message élève
if(!empty($this->Exercice->InfosEleve))
{
	$zip->addFromString("InfosEleve.txt", $this->Exercice->InfosEleve);
}

//Message correcteur
if(!empty($this->Exercice->InfosCorrecteur))
{
	$zip->addFromString("InfosCorrecteur.txt", $this->Exercice->InfosCorrecteur);
}

foreach($this->Files as $Type => $Fichiers)
{
	foreach($Fichiers as $URL => $_)
	{
		$zip->addFile(PATH . '/public/exercices/' . $this->Exercice->LongHash . $URL, $URL);
	}
}

$zip->close();

//Envoyer le zip
header("Content-Type: application/zip");
header("Content-Length: " . filesize($ZipURL));
header('Content-Disposition: attachment; filename="' . $this->Exercice->filterTitle() . '.zip"');
readfile($ZipURL);
?>