<?php 
echo $this->View_render($this->Compte, 1);
echo $this->View_render($this->Matieres, 1);
?>

<h2>Autres options</h2>
<?php 
$Actions = array
(
	'desinscription'=> array(
		'Fermer mon compte',
		'Vous pouvez vous désinscrire défintivement d\'' . $this->Html_eDevoir() . '.',
		'desinscription',
	), 
	'points/retrait' => array(
		'Retirer des points',
		'Vous avez bien travaillé ? Alors pourquoi ne pas transformer vos points en argent !',
		'retrait'
	),
);

echo $this->Html_listAction($Actions, '/correcteur/__URL__', 'correcteur');