<?php 
echo $this->View_render($this->Membre);
?>

<h2 id="administrateur-membre-correcteur">Informations correcteur</h2>
<p class="intro">Cette section affiche les différentes informations de la personne demandée en tant que correcteur</p>

<?php
$Infos = array(
	'Identité' => $this->Correcteur->Prenom . ' ' . strtoupper($this->Correcteur->Nom),
	'SIRET' => $this->Correcteur->Siret . '(' . ($this->Correcteur->SiretOK?'<span style="color:green">valide</span>':'<span style="color:red;">non validé</span>') . ')',
	'Exercices attitrés' => $this->NbExos,
	'Note moyenne' => $this->Note,
);

$Liste = array();
foreach($Infos as $Caption => $Info)
{
	$Liste[] = '<strong>' . $Caption . '</strong>&nbsp;: ' . $Info;
}

echo $this->Html_list($Liste);
?>

<h2 class="h2_exercice" id="administrateur-membre-correcteur-exercices">Exercices réservés par ce correcteur</h2>
<?php 
$Liste = array();
foreach($this->Exos as $Hash => $Contenu)
{
	$Contenu['Expiration'] = strtotime($Contenu['Expiration']);
	$Parts = array();
	
	if($Contenu['Expiration'] > time())
	{
		$Parts[] = 'Expiration dans ' . $this->Date_countdown($Contenu['Expiration']);
	}
	else
	{
		$Parts[] = 'Expiré depuis le ' . date('d/m/Y', $Contenu['Expiration']) . '.';
	}
	
	if(!empty($Contenu['Enchere']))
	{
		$Parts[] = 'Prix demandé : ' . $this->Points($Contenu['Enchere']);
	}
	
	$Parts[] = 'Statut : ' . $Contenu['Statut'];
	
	$Liste[$Hash] = array(
		$Contenu['Titre'],
		implode('<br />', $Parts)
	);
}

echo $this->Html_listAction($Liste, '/administrateur/exercice/index/__URL__');
?>

<h2 class="h2_actions" id="administrateur-membre-correcteur-actions">Actions disponibles</h2>
<p class="intro">Cette section affiche les différentes actions possibles pour ce compte.</p>

<?php
$Actions = array(
	'incarner' => array(
		'Me faire passer pour ce correcteur',
		'Simuler une connexion sur ce compte'
	),
	'statut' => array(
		'Modifier le statut du compte',
		'Bloquer ou désinscrire le compte'
	),
);

echo $this->Html_listAction($Actions, '/administrateur/membre/__URL__/' . $this->Correcteur->Mail);
	
?>