<?php 
echo $this->View_render($this->Membre);
?>

<h2 class="administrateur-membre-eleve">Informations élève</h2>
<p class="intro">Cette section affiche les différentes informations de la personne demandée en tant qu'élève</p>

<?php
$Infos = array(
	'Classe' => $this->Eleve->DetailsClasse,
	'Section' => $this->Eleve->Section,
	'Exercices créés' => $this->NbExos
);

$Liste = array();
foreach($Infos as $Caption => $Info)
{
	$Liste[] = '<strong>' . $Caption . '</strong>&nbsp;: ' . $Info;
}

echo $this->Html_list($Liste);
?>

<h2 class="h2_exercice">Exercices créés par l'élève</h2>
<?php 
$Liste = array();
foreach($this->Exos as $Hash => $Contenu)
{
	$Contenu['Expiration'] = strtotime($Contenu['Expiration']);
	$Parts = array();
	
	if($Contenu['Expiration'] > time())
	{
		$Parts[] = 'Expiration dans ' . $this->Date_countdown($Contenu['Expiration']);
	}
	else
	{
		$Parts[] = 'Expiré depuis le ' . date('d/m/Y', $Contenu['Expiration']) . '.';
	}
	
	if(!empty($Contenu['Enchere']))
	{
		$Parts[] = 'Prix demandé : ' . $Contenu['Enchere'] . 'pts';
	}
	
	$Parts[] = 'Statut : ' . $Contenu['Statut'];
	
	$Liste[$Hash] = array(
		$Contenu['Titre'],
		implode('<br />', $Parts)
	);
}

echo $this->Html_listAction($Liste, '/administrateur/exercice/index/__URL__');
?>

<h2 class="h2_actions">Actions disponibles</h2>
<p class="intro">Cette section affiche les différentes actions possibles pour ce compte.</p>

<?php
$Actions = array(
	'incarner' => array(
		'Me faire passer pour cet élève',
		'Simuler une connexion sur ce compte'
	),
	'statut' => array(
		'Modifier le statut du compte',
		'Bloquer ou désinscrire le compte'
	),
);

echo $this->Html_listAction($Actions, '/administrateur/membre/__URL__/' . $this->Eleve->Mail);
	
?>