<?php
$Statuts = array(
	'OK' => 'en fonctionnement',
	'EN_ATTENTE' => 'en attente de validation',
	'BLOQUE' => '<span style="color:red;">bloqué</span>',
	'DESINSCRIT' => 'désinscrit'
);

$Infos = array(
	'Mail' => $this->Membre->Mail,
	'Points' => $this->Points($this->Membre->getPoints()),
	'Création du compte' => date('d/m/Y', strtotime($this->Membre->Creation)),
	'Dernière connexion' => date('d/m/Y à H:i', strtotime($this->Membre->Connexion)),
	'Statut du compte' => $Statuts[$this->Membre->Statut],	
);

$Liste = array();
foreach($Infos as $Caption => $Info)
{
	$Liste[] = '<strong>' . $Caption . '</strong>&nbsp;: ' . $Info;
}

echo $this->Html_list($Liste);
?>