<table>
<caption><a href="http://edevoir.com">eDevoir.com</a></caption>
<tr>
	<td><img src="http://edevoir.com/public/images/mail/logo.png" alt="Mail eDevoir"></td>
</tr>
<tr>
	<td>
		__BONJOUR__
	</td>
</tr>
<tr>
	<td>
		<hr />
	</td>
</tr>
<tr>
	<td>
		__CONTENU__
	</td>
</tr>
<tr>
	<td>
		<p>
			<a href="http://edevoir.com/documentation/">Accéder à la documentation </a> &ndash;
			<a href="http://edevoir.com/contact.htm">Nous contacter</a>
		</p>
	</td>
</tr>
</table>
<p>À bientôt sur eDevoir !</p>