<table align="center" width="600px" cellpadding="0" cellspacing="0" =style="border-collapse:collapse; margin:0 auto; text-align:left;">

<tr>
	<td align="center" width="261px" height="61px"><a href="http://edevoir.com"><img src="http://edevoir.com/public/images/mail/logo.png" alt="http://edevoir.com"></a></td>
</tr>
<tr>
	<td style="font-family:Arial, Helvetica, sans-serif; font-size:20px; line-height:100%; padding:20px 0 0 0;">
		__BONJOUR__
	</td>
</tr>
<tr>
	<td>
		<hr />
	</td>
</tr>
<tr>
	<td>
		__CONTENU__
	</td>
</tr>
<tr>
	<td style="padding:20px 0 0 0;">
		<p align="center" width="100%">
			<a href="http://edevoir.com/documentation/">Accéder à la documentation </a> &ndash;
			<a href="http://edevoir.com/contact.htm">Nous contacter</a>
		</p>
	</td>
</tr>
</table>
<p align="center" width="600px">À bientôt sur eDevoir !</p>