<!DOCTYPE html>
<html>
<head>
	<meta charset=utf-8 />
<?php echo $this->renderHead(); ?>
	<!--[if IE]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body>

<?php 
//Gestion des messages
if($this->issetMeta('message')) {?>
<aside id="message" class="<?php echo $this->getMeta('messageClass') ?>"><?php echo $this->getMeta('message') ?></aside>
<?php }?>

<section id="content">
<?php include $this->getMeta('viewFile');?>
</section>

</body>
</html>