<!DOCTYPE html>
<html>
<head>
	<meta charset=utf-8 />
<?php echo $this->renderHead(); ?>
	<!--[if IE]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body>

<section id="ribbon">
	<?php 
	//Gestion du ruban
	echo $this->renderRibbon()
	?>
</section>

<section id="content">
	<?php 
	//Gestion des messages
	echo $this->renderMessage()
	?>
	
	<?php
	//Et le contenu de la page.
	include $this->getMeta('viewFile');
	?>
</section>

</body>
</html>