<!DOCTYPE html>
<html>
<head>
	<meta charset=utf-8 />
<?php echo $this->renderHead(); ?>
	<!--[if IE]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body>

<section id="ribbon">
<?php 
	//Gestion du ruban
	echo $this->renderRibbon()
?>
</section>

<section id="logo">
	<section>
	<!-- Mettre le logo ici -->
	</section>
	<section>
	<!-- Mettre les liens ici -->
	</section>
</section>

<section id="ariane">
<?php 
	//Gestion du ruban
	echo $this->renderBreadcrumbs()
?>
</section>

<section id="content">
<?php 
	//Gestion des messages
	echo $this->renderMessage()
?>
	
<?php
	//Et le contenu de la page.
	$this->renderContent();
?>
</section>

</body>
</html>