<p>Avant de commencer à travailler, quelques rappels :</p>
<?php 
$Rappels = array();

$Rappels[] = 'Délai avant expiration : ' . $this->Date_countdown($this->Exercice->Expiration);
$Rappels[] = 'Type de la demande : <strong>' . $this->Exercice->DetailsDemande . '</strong>. ' . $this->Doc_anchor('correcteur', 'demande_' . strtolower($this->Exercice->Demande));

echo $this->Html_list($Rappels);
?>
<p>Vous retrouverez l'exercice au complet ci-dessous.</p>

<div id="tabs">
	<ul>
		<li><a href="#envoi-texte">Source TeX</a></li>
		<li><a href="#envoi-apercu">Aperçu</a></li>
		<li><a href="#envoi-log">Console</a></li>
	</ul>
	<div id="envoi-texte">
		<form id="form_envoi-exercice" method="post" action="">
		<?php
		echo $this->Form_textareaLabelBr(
			'corrige',
			'Votre texte',
			array(
				'required' => 'required',
				'style' => 'height:720px;',
				'value' => '\maketitle
\LaTeX{} is a document preparation system for the \TeX{} typesetting program. It offers programmable desktop publishing',
			)
		);
		echo $this->Doc_inputBr('correcteur', 'aide_tex');
		
		echo $this->Form_input('apercu-exercice', array('type' => 'button', 'value' => 'Prévisualiser'));
		echo $this->Form_submit('envoi-exercice', "Envoyer ce texte");
		?>
		</form>
	</div>
	<div id="envoi-apercu">
	</div>
	<div id="envoi-log">
		<pre id="pre_envoi-log">
		Aucune information disponible pour l'instant.
		<a href="#" class="compiler">Prévisualiser maintenant</a>.
		</pre>
	</div>
</div>

<?php 
echo $this->Exercice($this->Exercice);
?>

<!-- Texte affiché pendant la compilation -->
<div id="modal" title="Information">
</div>
