<?php
//Index de l'exercice

/**
 * Liste des actions possibles.
 * Structure :
 * Statut =>
 * 	action =>
 * 		lien => caption[[, explication], documentation]
 * 
 * @var array
 */
$ListeActions = array(
	'ATTENTE_CORRECTEUR' => array(
		'reservation' => array('Faire une offre', 'Vous pouvez faire une proposition à l\'élève.')
	),
	'ATTENTE_ELEVE' => 'Aucune action n\'est actuellement disponible pour cet exercice. Vous serez informé si l\'élève vous accepte.',
	'EN_COURS' => array(
		'envoi' => array('Rédiger le corrigé', 'Votre offre a été acceptée, vous pouvez donc écrire le corrigé.')
	),
	'ENVOYE' => 'Votre exercice a été transmis. Vous serez payé dès que l\'élève aura donné son accord (ou au plus tard le ' . date('d/m/y à H\h', strtotime($this->Exercice->Expiration) + DELAI_REMBOURSEMENT * 24 * 3600) . ')',
	'TERMINE' => 'Votre correction a été acceptée et jugée comme valide. Vous avez dû être payé.',
	'REFUSE' => 'Suite à une demande de l\'élève, nous vérifions la pertinence de votre travail. Vous serez informé de nos conclusions dès que possible. ' . $this->Doc_anchor('correcteur', 'qualite'),
	'REMBOURSE' => 'Des failles dans votre travail nous ont conduit à rembourser l\'élève (en lui reversant <strong>' . $this->Exercice->Remboursement . '%</strong> du prix original). Que cela ne se reproduise plus ;)',
);
?>

<p class="infos">Une fois cet exercice réalisé et validé, vous serez payé <?php echo $this->Points($this->Exercice->priceAsked()) ?>.</p>
<h2 class="h2_actions" id="correcteur-exercice-index-options">Options de l'exercice</h2>

<?php
$Actions = $ListeActions[$this->Exercice->Statut];
if(!is_array($Actions))
{
	echo '<p>' . $Actions . '</p>';
}
else
{
	echo $this->Html_listAction($Actions, '/correcteur/exercice/__URL__/' . $this->Exercice->Hash, 'correcteur');
}
?>

<h2 class="h2_exercice" id="correcteur-exercice-index-affichage">Affichage de l'exercice</h2>
<?php 
echo $this->Exercice($this->Exercice);
?>

<h2 class="h2_logs" id="correcteur-exercice-index-actions">Actions sur l'exercice</h2>
<?php 
echo $this->Html_ajaxTable('/correcteur/exercice/_actions/' . $this->Exercice->Hash, 'Actions sur l\'exercice', array('Date', 'Action'));
?>