<?php
/**
 * Liste des actions possibles.
 * Structure :
 * Statut =>
 * 	action =>
 * 		lien => caption[[, explication], documentation]
 * 
 * @var array
 */
$ListeActions = array(
	'ATTENTE_CORRECTEUR' => array(
		'reservation' => array('Faire une offre', 'Vous pouvez faire une proposition à l\'élève.')
	),
	'ATTENTE_ELEVE' => 'Aucune action n\'est actuellement disponible pour cet exercice. Vous serez informé si l\'élève vous accepte.',
	'EN_COURS' => array(
		'envoi' => array('Rédiger le corrigé', 'Votre offre a été acceptée, vous pouvez donc écrire le corrigé.')
	),
	'ENVOYE' => 'Votre exercice a été transmis. Vous serez payé dès que l\'élève aura donné son accord (ou que le délai est dépassé)'
);
?>

<h2>Options de l'exercice</h2>

<?php
$Actions = $ListeActions[$this->Exercice->Statut];
if(!is_array($Actions))
{
	echo '<p>' . $Actions . '</p>';
}
else
{
	echo $this->Html_listAction($Actions, '/correcteur/exercice/_URL_/' . $this->Exercice->Hash, 'correcteur');
	//TODO : un select "quickjump" pour activer rapidement différentes options.	
}
?>

<h2>Affichage de l'exercice</h2>
<?php 
echo $this->Exercice($this->Exercice);
?>

<h2>Actions sur l'exercice</h2>
<?php 
echo $this->Html_ajaxTable('/correcteur/exercice/_actions/' . $this->Exercice->Hash, 'Actions sur l\'exercice', array('Date', 'Action'));
?>