<?php 
if(count($this->ExercicesActifs) > 0)
{
	?>
	<h2 id="membre-exercice-index-actif">Mes exercices actifs</h2>
	<p>Vous vous êtes engagés à corriger ces exercices.</p>
	<?php 
	$ExercicesActifs = array();
	foreach($this->ExercicesActifs as $Hash => $Donnees)
	{
		$ExercicesActifs[] = '<a href="/correcteur/exercice/envoi/' . $Hash . '">' . $Donnees['Titre'] . '</a> (expiration : ' . $this->Date_countdown($Donnees['Expiration']) . ')';
	}
	echo $this->Html_list($ExercicesActifs, 'ul', 'ul_exercices-actifs');
}

if(count($this->QuestionsActives) > 0)
{
	?>
	<h2 id="membre-exercice-index-faq">Questions en suspens</h2>
	<p>Des questions sans réponse attendent désespérement votre passage pour les éclairer de votre lumière.</p>
	<?php 
	$Questions = array();
	foreach($this->QuestionsActives as $Hash => $Donnees)
	{
		$Questions[] = '<a href="/correcteur/exercice/faq/' . $Hash . '">' . $Donnees['Titre'] . '</a>&nbsp;: ' . ($Donnees['NbQuestions'] == 1?'une question':$Donnees['NbQuestions'] . ' questions') . ' en suspens.';
	}
	echo $this->Html_list($Questions, 'ul', 'ul_questions_actives');
}
?>

<h2 class="h2_logs" id="correcteur-exercice-index-actions">Dernières actions</h2>
<?php 
echo $this->Html_ajaxTable('/correcteur/exercice/_actions', 'Actions sur vos exercices', array('Date', 'Exercice', 'Action'));
?>