<?php 
echo $this->Exercice($this->Exercice);
?>

<?php 
echo $this->Doc_box('correcteur','reservation','Besoin d\'aide pour compléter ce formulaire ?');
?>

<form id="form_reservation-exercice" method="post" action="">
<p>Consultez le sujet.<br />
Si vous vous sentez prêt, indiquez votre prix puis cliquez sur valider. Faites-vite, vous n'êtes pas seul !</p>

<?php
//Prix
echo $this->Form_inputLabel(
	'prix',
	'Prix demandé', 
	array(
		'value' => 1000,
		'type' => 'number',
		'min' => 0,
		'max' => 20000,
		'step' => 25,
	)
) . $this->Doc_inputBr('correcteur', 'prix');
//TODO: documentation/correcteur/prix

echo $this->Form_submit('reservation-exercice', "Réserver l'exercice");
?>
</form>