<h2 id="administrateur-index-index-dashboard">Tableau de bord administrateur</h2>
<p>D'abord, on flâne un peu en consultant ces statistiques inutiles. <a href="/admin/logs/">Plus de stats ?</a></p>
<?php 
echo $this->Html_ajaxTable('/administrateur/log/_global', 'Statistiques globales', array('Action', '24h', '48h', '7j'));
?>

<h2 class="h2_actions" id="administrateur-index-index-attente">En attente</h2>
<?php 
$Attentes = array();

if($this->Virements != 0)
{
	$Attentes['virements'] = array(
		$this->Virements . ' virement' . ($this->Virements==1?'':'s') . ' en attente',
		'Ces virements devraient être réalisés dans les plus brefs délais.'
	);
}

if($this->Alertes != 0)
{
	$Attentes['alertes'] = array(
		$this->Alertes . ' alerte' . ($this->Alertes==1?'':'s') . ' en attente',
		'Des alertes ont été générées, elles demandent l\'avis d\'un exepert.'
	);
}

if($this->Reclamations != 0)
{
	$Attentes['reclamations'] = array(
		$this->Reclamations . ' réclamation' . ($this->Reclamations==1?'':'s') . ' en attente',
		'Certains élèves ne sont pas content du corrigé proposé.'
	);
}

if($this->Validations != 0)
{
	$Attentes['validations'] = array(
		$this->Validations . ' validation' . ($this->Validations==1?'':'s') . ' en attente',
		'Certains correcteurs nécessitent votre approbation avant de pouvoir commencer à travailler.'
	);
}

if(empty($Attentes))
{
	?>
	<p>Rien n'est en attente. Pourquoi ne pas ouvrir une bouteille de champagne en attendant que du travail arrive ?</p>
	<?php 
}
else
{
	?>
	<p>Maintenant au boulot ! Les catégories ci-dessous attendent une action de votre part.</p>
	<?php 
	echo $this->Html_listAction($Attentes, '/administrateur/__URL__', '');
}
?>

<h2 class="h2_actions" id="administrateur-index-index-liens">Liens</h2>
<?php 
$Actions = array(
	'membre/' => 'Rechercher un membre',
	'log/' => 'Index des logs',
	'log/eleve' => array(
		'Logs élèves',
		'Informations sur les élèves'
	),
	'log/correcteur' => array(
		'Logs correcteurs',
		'Informations sur les correcteurs',
	),
	'log/membre' => array(
		'Log membres',
		'Informations sur les membres en général',
	),
	'bannis' => array(
		'IPs bannies',
		'Bannir ou débannir des adresses IP'
	),
);

echo $this->Html_listAction($Actions, '/administrateur/__URL__');
?>