<?php
//Liste des virements à effectuer
/**
 * Crée un tableau affichable à partir d'un équivalent tuple SQL
 * 
 * @param array $Tuple
 * 
 * @return array un tableau colonne utilisable
 */
function formatTuple(array $Tuple)
{
	$Tuple['Date'] = date('d/m/Y à H\h', strtotime($Tuple['Date']));
	
	return $Tuple;
}

$Head = array('Date', 'Membre', 'Montant', 'Bénéficiaire', 'Action');
?>

<p>En attente : <?php echo $this->NbVirements; ?></p>

<h2 id="administrateur-index-virements-rib">Virements par RIB</h2>

<table>
<?php 
echo $this->Html_tableHead('Virements RIB', $Head)
?>
<tbody>
<?php 
foreach($this->VirementsRib as $Tuple)
{
	echo $this->Html_tableRow(formatTuple($Tuple));
}
?>
</tbody>
</table>

<h2 id="administrateur-index-virements-paypal">Virements par Paypal</h2>

<table>
<?php 
echo $this->Html_tableHead('Virements Paypal', $Head)
?>
<tbody>
<?php 
foreach($this->VirementsPaypal as $Tuple)
{
	echo $this->Html_tableRow(formatTuple($Tuple));
}
?>
</tbody>
</table>