<?php 
$Possibilites = array(
	'again'=>"Je veux sauvegarder cet exercice pour y revenir plus tard (cette action ne vous fera pas quitter la page).",
	'resume'=>"J'ai terminé d'ajouter des fichiers. Passer à la dernière étape.");

//Taille maximum.
$SizeLimit = '<input type="hidden" name="MAX_FILE_SIZE" value="' . $this->SizeLimit . '" />'; 

if(!empty($this->Exercice->InfosEleve))
{
	echo '<p class="infos">Si vous avez marqué votre exercice dans le champ « informations complémentaires » et ne souhaitez pas ajouter de fichier, vous pouvez <a href="/eleve/exercice/recapitulatif/' . $this->Exercice->Hash . '">passer directement à la dernière étape</a>.</p>';
}
echo $this->Doc_box('eleve', 'ajout', "Besoin d'aide pour compléter ce formulaire ?");
?>

<?php 
if($this->NbFiles > 0)
{?>
	<p>Vous avez déjà envoyé <?php echo $this->NbFiles; ?> fichier<?php echo ($this->NbFiles==1?'':'s') ?> pour cet exercice.</p>
	<?php 
}
?>
<div id="tabs">
	<ul>
		<li><a href="#ajout-noscript">Ajout sans Javascript</a></li>
		<li><a href="#ajout-basique">Ajout basique</a></li>
		<li><a href="#ajout-complet">Ajout complet</a></li>
	</ul>
	<div id="ajout-noscript">
		<p>Cet onglet sert aux personnes ayant désactivées Javascript.<br />
		Si vous le pouvez, préférez utiliser l'<a href="#ajout-complet" onclick="$('#tabs').tabs('select', 2);">ajout complet</a>.</p>
		
		<?php
			echo $this->Doc_box(
				'eleve',
				'fichiers',
				"Attention ! Tous les types de fichiers ne sont pas autorisés.<br />
				Extensions autorisées : " . str_replace('|', ', ', EXTENSIONS) . '.'
			);
		?>
		
		<p>Ne remplissez que les champs nécessaires, puis cliquez sur envoyer.</p>
		<form method="post" enctype="multipart/form-data" action="" id="form_upload-noscript">
		<?php 
		echo $SizeLimit . PHP_EOL;
for($i=0; $i < $this->NbFilesUpload; $i++)
		{
			echo $this->Form_input(
				'fichiers[]',
				array(
					'type' => 'file',
				)
			) . "<br />\n";
}
		?>
		
		<p>Que faire ensuite ?</p>
		<?php 
		echo $this->Form_radio('next_page', $Possibilites, 'resume', 'script_');
		echo $this->Form_submit('upload-noscript', 'Envoyer les fichiers')
		?>
		</form>
	</div>
	<div id="ajout-basique">
		<p>Cet onglet sert aux personnes ne disposant pas de Flash ou étant bloquée par un pare-feu.<br />
		Si vous le pouvez, préférez utiliser l'<a href="#ajout-complet" onclick="$('#tabs').tabs('select', 2);">ajout complet</a>.</p>

		<p>Cet onglet permet d'ajouter des fichiers à votre exercice.<br />
		Sélectionnez vos fichiers un par un, puis cliquez sur Envoyer.</p>
		
		<form method="post" enctype="multipart/form-data" action="" id="form_upload-script">
		<?php echo $SizeLimit . PHP_EOL;
if($this->NbFilesUpload > 0)
		{?>
			<input type="file" name="fichiers[]" id="fichiers" accept="<?php echo EXTENSIONS ?>" maxlength="<?php echo $this->NbFilesUpload ?>" />
			<?php 
}
else
		{
		?>
			<p>Vous ne pouvez plus ajouter de fichiers sur cet exercice.</p>
		<?php 
}
		?>	
		
		<p>Que faire ensuite ?</p>
		
		<?php 
		echo $this->Form_radio('next_page', $Possibilites, 'resume', 'noscript_');
		echo $this->Form_submit('upload', 'Envoyer les fichiers')
		?>
		</form>
	</div>
	<div id="ajout-complet">
		<p>Non implémenté pour l'instant.</p>
	</div>
</div>

