<?php 
if($this->EstRemboursable == true)
{
	?>
	<p>Vous êtes actuellement éligible pour un remboursement.<br />
	En envoyant votre demande, celle-ci sera analysée par une commission indépendante des correcteurs qui vous fera part de ses retours.<br />
	Si un remboursement doit avoir lieu, il se fera sous forme de points que vous pourrez ensuite <a href="/eleve/points/retrait">retirer</a>.</p>
	<?php
}
else
{
	?>
	<p class="important">Vous allez émettre une contestation « tardive ». L'exercice est normalment terminé, et le correcteur a déjà été payé.<br />
	Vous ne pourrez donc pas être remboursé.<br />
	En revanche, en constestant, vous nous permettez de vérifier la qualité du travail. Si celui-ci est effectivement mauvais, nous pourrons dès lors bloquer le correcteur pour éviter qu'il ne commette d'autres erreurs.</p>
	<?php
}

$Possibilites = array(
	'again'=>"Je veux sauvegarder cet exercice pour y revenir plus tard (cette action ne vous fera pas quitter la page).",
	'resume'=>"J'ai terminé d'ajouter des fichiers. Passer à la dernière étape.");

//Taille maximum.
$SizeLimit = '<input type="hidden" name="MAX_FILE_SIZE" value="' . $this->SizeLimit . '" />'; 

echo $this->Doc_box('eleve', 'contestation', "Besoin d'aide pour compléter ce formulaire ?");
?>

<form id="form_contestation-exercice" method="post" action="" enctype="multipart/form-data">
<?php 
echo $this->Form_textareaLabelBr('message', 'Justifiez votre demande');
?>
<p>Merci d'être précis et complet dans ce message. Plus vos griefs seront clairs, plus il sera facile de les juger.</p>

<p>Vous pouvez aussi envoyer des fichiers (scan d'un corrigé fait en classe, remarques du professeur...)</p>
<?php
echo $this->Doc_box(
	'eleve',
	'fichiers',
	"Attention ! Tous les types de fichiers ne sont pas autorisés.<br />
	Extensions autorisées : " . str_replace('|', ', ', EXTENSIONS) . '.'
);
echo $SizeLimit . "\n";
?>
<input type="file" name="fichiers[]" id="fichiers" accept="<?php echo EXTENSIONS ?>" maxlength="<?php echo $this->NbFilesUpload ?>" />

<?php
echo $this->Form_submit('contestation-exercice', 'Envoyer cette réclamation')
?>
</form>
