<?php 
echo $this->Doc_box('eleve', 'ajout', 'Besoin d\'aide pour compléter ce formulaire ?');
?>
<form id="form_creation-exercice" method="post" action="">
<p>Merci de remplir les champs suivants. L'envoi de fichiers se fera à la prochaine étape.</p>

<h3>Classe et matières</h3>
<?php
//Classe
echo $this->Form_selectLabelBr('classe', 'Niveau de l\'exercice', $this->Classes, $_SESSION['Eleve']->Classe);

//Section
echo $this->Form_inputLabelBr(
	'section',
	'Section (si nécessaire)',
	array(
		'placeholder' => 'S, ES, L...',
		'value'=>$_SESSION['Eleve']->Section
	)
);

//Matière
echo $this->Form_selectLabelBr('matiere', 'Matière', $this->Matieres);
?>

<h3>Demande</h3>
<p>Donnez un nom clair à votre exercice. Vous devriez être capable de vous en souvenir rien qu'en lisant son titre !<br />
<?php
//Nom de l'exercice
echo $this->Form_inputLabelBr(
	'titre',
	'Nom de l\'exercice',
	array(
		'placeholder' => 'DM de maths décembre',
		'maxlength' => 50,
		'required' => 'required'
	)
);
?>
</p>

<?php
//Type de l'exercice
echo $this->Form_selectLabelBr('type', 'Type de l\'exercice', $this->Types);

//Type de la demande
echo $this->Form_selectLabelBr('demande', 'Demande', $this->Demandes, 'COMPLET');
?>

<h3>Dates</h3>
<p>Tout d'abord, indiquez la date butoir à laquelle le corrigé <strong>doit</strong> vous être rendu. Il s'agit de la date limite finale, si vous n'avez rien à ce moment là vous serez remboursé.<br />
<?php
$HeureData = array(
	'type' => 'number',
	'min'=>0,
	'max'=>23,
	'step'=>1,
	'maxlength'=>2,
	'placeholder' => 'HH',
	'size'=>2,
	'required' => 'required',
	'class' => 'input_default'
);

//Rendu
$HeureData['value'] = 21;
echo $this->Form_inputLabel(
	'rendu_date',
	'Date de rendu',
	array(
		'value'=> date('d/m/Y', time()+3600*24*7),
		'placeholder' => 'JJ/MM/AAAA',
		'required' => 'required'
	)
);
echo 'à ' . $this->Form_input('rendu_heure', $HeureData) . 'h ' . $this->Doc_input('eleve', 'champ_rendu');
?>
</p>

<p>Ensuite, indiquez-nous à quel moment vous préférez abandonner automatiquement votre demande <strong>si aucune offre ne vous a conquis à cette date</strong>. Bien évidemment, cette date doit précéder la date de rendu !<br />
<?php
//Annulation automatique
$HeureData['value'] = 18;
echo $this->Form_inputLabel(
	'annulation_date',
	'Date d\'annulation',
	array(
		'value'=> date('d/m/Y', time()+3600*24*3),
		'placeholder' => 'JJ/MM/AAAA',
		'required' => 'required',
		'pattern' => '[0-3][0-9]/[0-1][0-9]/201[1-9]'
	)
);
echo 'à ' . $this->Form_input('annulation_heure', $HeureData) . 'h ' . $this->Doc_inputBr('eleve', 'champ_annulation');
?>
</p>

<h3>Informations complémentaires</h3>
<?php
echo $this->Form_textareaLabelBr('infos', 'Informations complémentaires', array('class' => 'tex-container'));
echo $this->Doc_input('eleve', 'champ_info') . PHP_EOL;
?>

<h3>Options avancées</h3>
<fieldset>
	<legend><input id="avance" type="checkbox" /><label for="avance">Afficher les options avancées</label></legend>

	<div id="div_auto-accept">
		<?php 
			echo $this->Form_pointsLabel(
				'auto_accept',
				'Valeur maximale d\'acceptation automatique', 
				$_SESSION['Eleve']->getPoints()
			);
			echo $this->Doc_inputBr('eleve', 'auto_accept');
		?>
		<div id="slider_auto-accept">Valeur maximum : <span><?php echo $_SESSION['Eleve']->getPoints(); ?></span></div>
	</div>
</fieldset>

<h3>Envoi du formulaire</h3>
<?php 
echo $this->Points_raiseWarning($this->getController()->getMembre());
?>
<p>Tout est prêt ? Cliquez sur le bouton ci-dessous pour passer à l'étape suivante et envoyer les fichiers constituant l'exercice.</p>
<?php
echo $this->Form_submit('creation-exercice', "Créer l'exercice");
?>
</form>
