<h1>Création d'un nouvel exercice</h1>
<p class="intro">Vous allez ajouter un nouvel exercice. Soyez le plus complet possible afin que nous puissions vous offrir un service de qualité !</p>

<?php //TODO : getRaise() ?>

<form id="form_creation-exercice" method="post" action="">

<h3>Classe et matières</h3>
<?php
//Classe
echo $this->Form_selectLabelBr('classe','Niveau de l\'exercice', $this->Classes, $_SESSION['Eleve']->Classe);

//Section
echo $this->Form_inputLabelBr('section', 'Section (si nécessaire)',
	array(
		'placeholder'=>'S, ES, L...',
		'value'=>$_SESSION['Eleve']->Section
	));

//Matière
echo $this->Form_selectLabelBr('matiere','Matière', $this->Matieres);
?>

<h3>Demande</h3>
<?php
//Type de l'exercice
echo $this->Form_selectLabelBr('type','Type de l\'exercice', $this->Types);

//Type de la demande
echo $this->Form_selectLabelBr('type','Demande', array(
		'COMPLET'=>'Corrigé complet',
		'AIDE'=>'Pistes de résolution',
	));
?>

<h3>Dates</h3>
<?php
//Rendu
echo $this->Form_inputLabel('rendu_date', 'Date de rendu',
	array(
		'value'=> date('d/m/y',time()+3600*24*7),
		'placeholder'=>'JJ/MM/AA'
	));
echo 'à ' . $this->Form_input('rendu_heure',
	array(
		'value'=> 21,
		'placeholder'=>'HH'
	)) . "h<br />\n";

//Annulation automatique
echo $this->Form_inputLabel('annulation_date', 'Date d\'annulation',
	array(
		'value'=> date('d/m/y',time()+3600*24*3),
		'placeholder'=>'JJ/MM/AA'
	));
echo 'à ' . $this->Form_input('annulation_heure',
	array(
		'value'=> 21,
		'placeholder'=>'HH'
	)) . "h<br />\n";
?>

<h3>Informations complémentaires</h3>
<?php
echo $this->Form_textareaLabelBr('infos','Informations complémentaires');
?>

<h3>Options avancées</h3>
<fieldset>
	<legend><input id="avance" type="checkbox" /><label for="avance">Afficher les options avancées</label></legend>

	<div id="div_auto-accept">
		<?php 
			echo $this->Form_inputLabelBr('auto_accept', 'Valeur maximale d\'acceptation automatique');
		?>
		<div id="slider_auto-accept">Valeur maximum : <span><?php echo $_SESSION['Eleve']->getPoints(); ?></span></div>
	</div>
</fieldset>

<h3>Envoi du formulaire</h3>
<?php
echo $this->Form_submit('creation-exercice',"Créer l'exercice");
?>
</form>
