<?php
/*
 * Quelques actions communes.
 */
$Annulation = array(
	'Annuler l\'exercice.',
	"Vous pouvez annuler l'exercice. Celui-ci ne vous sera pas facturé et ne comptera pas dans votre quota suractivité.",
	'supplement'
);

/**
 * Liste des actions possibles.
 * Structure :
 * Statut =>
 * 	action =>
 * 		lien => caption[[, explication], documentation]
 * 
 * @var array
 */
$ListeActions = array(
	'VIERGE' => array(
		'recapitulatif' => array('Mettre l\'exercice à disposition des correcteurs', 'Vous pouvez vérifier que toutes les informations nécessaires sont présentes, puis envoyer l\'exercice pour attendre une offre correcteur.', 'attente_correcteur'),
		'annulation' => $Annulation,
		'ajout' => array('Ajouter des fichiers', 'Vous pouvez continuer à ajouter des fichiers sur votre exercice.'),
	),
	'ATTENTE_CORRECTEUR' => array(
		'annulation' => $Annulation,
	),
	'ATTENTE_ELEVE' => array(
		'consultation_offre' => array('Voir l\'offre', "Consulter l'offre réalisée pour l'accepter ou la refuser.", 'offre'), 
		'annulation' => $Annulation,
	),
	'EN_COURS' => 'Aucune action n\'est actuellement disponible pour cet exercice. Vous serez informé lorsque le correcteur aura terminé sa correction.',
	'ENVOYE' => array(
		'sujet' => array('Revoir le sujet de l\'exercice', 'Pour bien se le remettre en tête !'),
		'corrige' => array('Consulter le corrigé envoyé', 'Lire le corrigé qui a été envoyé.')
	),
	'ANNULE' => 'Cet exercice a été annulé. <a href="/eleve/exercice/creation">Créer un nouvel exercice</a>.',
);
?>

<h2>Options de l'exercice</h2>

<?php
$Actions = $ListeActions[$this->Exercice->Statut];
if(is_array($Actions))
{
	foreach($Actions as $URL => &$Action)
	{
		if(is_array($Action))
		{
			$Texte = '<a href="/eleve/exercice/' . $URL . '/' . $this->Exercice->Hash . '">' . $Action[0] . '</a><br />
	<p class="exercice-action-detail">' . $Action[1];
			if(isset($Action[2]))
			{
				$Texte .= '<br />' . $this->Doc_anchor('eleve', $Action[2]);
			}
			
			$Action = $Texte . '</p>';
		}
		else
		{
			$Action = '<a href="' . $URL . '">' . $Action . '</a>';
		}
	}
	//TODO : un select "quickjump" pour activer rapidement différentes options.
	
	echo $this->Html_list($Actions);
}
else
{
	echo '<p>' . $Actions . '</p>';
}
?>

<h2>Affichage de l'exercice</h2>
<?php 
echo $this->Exercice($this->Exercice);
?>

<h2>Actions sur l'exercice</h2>
<?php 
echo $this->Html_ajaxTable('/eleve/exercice/_actions/' . $this->Exercice->Hash, 'Actions sur l\'exercice', array('Date', 'Action'));
?>