<?php
//Ne pas afficher le lien de création si la variable NoCreate existe.
//Cette variable est définie lors de l'inclusion de la vue dans une autre vue, par exemple sur /eleve/
//@see Eleve_IndexController::indexAction()
if(!isset($this->NoCreate))
{
	?>
	<h2 class="eleve-exercice-index-creation">Créer un nouvel exercice</h2>
	<?php 
	echo $this->Points_raiseWarning($this->getController()->getMembre());
	?>
	<a href="/eleve/exercice/creation">Créer un nouvel exercice</a>
	
	<?php
}
 
if(count($this->ExercicesActifs) > 0)
{
	$ExercicesActifs = array();
	foreach($this->ExercicesActifs as $Hash => $Datas)
	{
		$ExercicesActifs[$Hash] = array(
			$Datas['Titre'],
			'<em>' . $this->Messages[$Datas['Statut']] . '</em>'
		);
	}
	?>
	<h2 class="membre-exercice-index-actif">Mes exercices actifs</h2>
	<?php 
	echo $this->Html_listAction($ExercicesActifs, '/eleve/exercice/index/__URL__', 'eleve');
}
?>

<h2 class="h2_logs">Actions sur vos exercices</h2>
<?php 
echo $this->Html_ajaxTable('/eleve/exercice/_actions', 'Actions sur vos exercices', array('Date', 'Exercice', 'Action'));
?>