<?php 
echo $this->Doc_box(
	'eleve',
	'contestation',
	"Attention, en donnant une note, vous perdez la possibilité d'émettre une <a href=\"/eleve/exercice/contestation/" . $this->Exercice->Hash . '">réclamation</a> pour remboursement.'
);
?>

<form id="form_note-exercice" method="post" action="">
<p>Une note de 0 indique un travail clairement mal fait mais toutefois correct (complet, et ne nécessitant donc pas une réclamation).<br />
Une note de 5 indique un travail parfait.</p>
<?php 
echo $this->Form_selectLabelBr(
	'note',
	'Votre note',
	array(
		'0' => '&empty; – Catastrophique',
		'1' => '✭ &ndash; Nul',
		'2' => '✭✭ &ndash; Mauvais',
		'3' => '✭✭✭ &ndash; Moyen',
		'4' => '✭✭✭✭ &ndash; Bien',
		'5' => '✭✭✭✭✭ &ndash; Parfait'
	),
	3
);

echo $this->Form_textareaLabelBr(
	'message',
	'Si vous le souhaitez, vous pouvez justifier de votre note',
	array(
		'class' => 'tex-container'
	)
);

echo $this->Form_submit('note-exercice', 'Noter l\'exercice');
?>
</form>