<p>Vérifiez la cohérence de vos données, puis cliquez sur le bouton «&nbsp;Envoyer aux correcteurs&nbsp;».<br />
En cas de souci, corrigez les problèmes avant d'envoyer.</p>

<form method="post" action="" id="form_change-info">
<?php 
echo $this->Form_textareaLabelBr(
	'infos',
	'Informations associées à l\'exercice',
	array(
		'value' => $this->Exercice->InfosEleve,
	)
);
echo $this->Form_submit('change-info', 'Modifier ces informations, puis revenir sur cette page');
?>
</form>

<p><a href="/eleve/exercice/ajout/<?php echo $this->Exercice->Hash ?>">Retourner à l'ajout de fichiers.</a></p>

<?php echo $this->Exercice($this->Exercice); ?>

<?php 
echo $this->Form('recapitulatif-ok', 'resume', "Envoyer cet exercice aux correcteurs et attendre leurs offres.");
?>