<h1>Récapitulatif des données envoyées</h1>
<p class="intro">Vérifiez que vos données soient cohérentes, puis cliquez sur le bouton "Envoyer aux correcteurs".<br />
En cas de souci, corrigez les problèmes avant d'envoyer.</p>

<?php echo $this->Exercice($this->Exercice); ?>


<form method="post" action="" id="form_change-info">
<?php 
echo $this->Form_textareaLabelBr(
	'infos',
	'Informations associées à l\'exercice',
	array(
		'value' => $this->Exercice->InfosEleve,
	)
);
echo $this->Form_submit('change-info', 'Modifier ces informations et revenir sur cette page');
?>
</form>