<?php 
$Datas = array();
		
foreach($this->RawDatas as $Hash => $ExerciceDatas)
{
	$Expiration = '<a href="/correcteur/exercice/reservation/' . $Hash . '">Réserver l\'exercice</a><br />';
	$Expiration .= $this->Date_countdown($ExerciceDatas['TimeoutEleve']);
	
	$Infos = '<h2>' . $ExerciceDatas['Titre'] . '</h2>';
	$Infos .= '<p><strong>' . $ExerciceDatas['Matiere'] . '</strong>';
	if($ExerciceDatas['Section'] != '')
	{
		$Infos .= ' (' . $ExerciceDatas['Section'] . ')';
	}
	$Infos .= ', ' . $ExerciceDatas['DetailsClasse'];
	
	$Infos .= '<br />Demande : ' . $ExerciceDatas['DetailsDemande'];
	
	//Créer un objet Exercice pour afficher la remarque de l'élève (le VH prend un exercice en paramètre, et pas un tableau)
	//MOCHE
	$Cast = new Exercice();
	$Cast->InfosEleve = $ExerciceDatas['InfosEleve'];
	$Infos .= $this->Exercice_infos($Cast, 'Eleve');
	unset($Cast);
	
	$Infos .= '</p><p class="image-preview">';
	if(!is_null($ExerciceDatas['Sujets']))
	{
		$ExerciceDatas['Sujets'] = explode(',', $ExerciceDatas['Sujets']);
		$ExerciceDatas['SujetsThumbs'] = explode(',', $ExerciceDatas['SujetsThumbs']);
		$Sujets = array();
		for($i = 0; $i < count($ExerciceDatas['Sujets']); $i++)
		{
			$Sujets[$ExerciceDatas['SujetsThumbs'][$i]] = array(
				'URL' => $ExerciceDatas['Sujets'][$i],
				'alt' => 'Fichier #' . $i
			);
		}
		$Infos .= $this->Exercice_thumbs($Sujets, $ExerciceDatas['LongHash']);
	}
	
	$Infos .= '</p>';
	
	$Datas[] = array(
		$Expiration,
		$Infos
	);
}

echo json_encode($Datas);
?>