<form id="form_connexion-correcteur" method="post" action="">

<?php
echo $this->Form_inputLabelBr(
	'email',
	'Votre adresse mail',
	array(
		'type' => 'email',
		'placeholder' => 'nom@fai.fr',
		'required' => 'required',
	)
);
echo $this->Form_inputLabelBr(
	'password',
	'Votre mot de passe',
	array(
		'type' => 'password',
		'required' => 'required',
	)
);
echo $this->Form_submit('connexion-correcteur', "Connexion");
?>
</form>

<p class="see-link"><a href="/correcteur/recuperation">Mot de passe perdu ?</a></p>