<h2 class="correcteur-index-index-foire">Foire aux exercices</h2>
<?php 
$Foire = array(
	'liste' => array(
		'Accéder à la foire aux exercices',
		'Consulter la liste des exercices actuellement disponibles correspondant à vos compétences',
		'marche'
	),
	'options/matieres' => array(
		'Définir vos compétences',
		'Indiquer au site les matières dans lesquels vous êtes compétents.',
		'matieres'
	)
);

echo $this->Html_listAction($Foire, '/correcteur/__URL__', 'correcteur');
?>

<?php 
echo $this->View_render($this->Exo, 1);
echo $this->View_render($this->Points, 1);
?>