<h2 id="correcteur-index-index-marche">Marché aux exercices</h2>
<?php 
$Marche = array(
	'liste' => array(
		'Accéder au marché aux exercices',
		'Consulter la liste des exercices actuellement disponibles correspondant à vos compétences',
		'marche'
	),
	'options/matieres' => array(
		'Définir vos compétences',
		'Indiquer au site les matières dans lesquels vous êtes compétents.',
		'matieres'
	)
);

echo $this->Html_listAction($Marche, '/correcteur/__URL__', 'correcteur');
?>

<?php 
echo $this->View_render($this->Exo, 1);
echo $this->View_render($this->Points, 1);
?>