<?php 
echo $this->Doc_box('correcteur', 'inscription', 'Besoin d\'aide pour compléter ce formulaire ?');
?>
<form id="form_inscription-correcteur" method="post" enctype="multipart/form-data" action="">

<?php
echo $this->Form_inputLabelBr(
	'email',
	'Votre adresse mail',
	array(
		'type' => 'email',
		'placeholder' => 'nom@domaine.fr',
		'required' => 'required',
	)
);
echo $this->Form_inputLabelBr(
	'password',
	'Votre mot de passe',
	array(
		'type' => 'password',
		'required' => 'required',
	)
);
echo $this->Form_inputLabelBr(
	'password_confirm',
	'Confirmez votre mot de passe',
	array(
		'type' => 'password',
		'required' => 'required',
	)
);
	
echo $this->Form_inputLabelBr(
	'nom',
	'Votre nom',
	array(
		'placeholder' => 'Dupont',
		'required' => 'required',
	)
);

echo $this->Form_inputLabelBr(
	'prenom',
	'Votre prénom',
	array(
		'placeholder' => 'Jean',
		'required' => 'required',
	)
);

echo $this->Form_inputLabelBr(
	'telephone',
	'Votre numéro de téléphone',
	array(
		'type' => 'tel',
		'placeholder' => '06 00 00 00 00',
		'required' => 'required',
		'pattern' => '^0[1-8]([-. ]?[0-9]{2}){4}$'
	)
);

echo $this->Form_inputLabel(
	'cv',
	'Votre CV (PDF uniquement)',
	array(
		'type' => 'file',
		'required' => 'required',
	)
) . $this->Doc_inputBr('correcteur', 'pourquoi_cv');

echo $this->Doc_box(
	'correcteur',
	'comment_autoentreprise',
	"Vous devez nous fournir un numéro de SIRET valide. <strong>Si vous venez de vous inscrire en tant qu'auto-entrepreneur et que vous n'avez pas encore reçu votre numéro, vous pouvez laisser ce champ vide</strong>.<br />
	<strong>Attention, aucun paiement ne pourra être effectué tant que vous n'aurez pas fourni ce numéro.</strong>"
);

echo $this->Form_inputLabel(
	'siret',
	'Votre numéro de SIRET',
	array(
		'placeholder' => '000 000 000 00000',
		'pattern' => '^[0-9]{3} ?[0-9]{3} ?[0-9]{3} ?[0-9]{5}$'
	)
) . $this->Doc_inputBr('correcteur', 'pourquoi_autoentreprise');
?>
CGU Correcteurs<br />

<?php 
echo $this->Form_checkbox(
	'cgu',
	"J'ai lu et j'accepte les Conditions Générales d'Utilisation du site",
	false,
	array(
		'required' => 'required'
	)	
);

echo $this->Form_captcha();

echo $this->Form_submit('inscription-correcteur', "Me proposer comme correcteur");
?>
</form>