<form id="form_connexion-eleve" method="post" action="">

<?php
echo $this->Form_inputLabelBr(
	'email',
	'Votre adresse mail',
	array(
		'type' => 'email',
		'placeholder' => 'nom@domaine.fr',
		'required' => 'required'
	)
);
echo $this->Form_inputLabelBr(
	'password',
	'Votre mot de passe',
	array(
		'type' => 'password',
		'required' => 'required'
	)
);
echo $this->Form_submit('connexion-eleve', "Connexion");
?>
</form>

<p class="see-link"><a href="/eleve/recuperation">Mot de passe perdu ?</a></p>