<h1>Connexion élève</h1>
<p class="intro">Connectez-vous pour accéder au site.</p>
<p class="see-link"><a href="/eleve/inscription">Vous n'êtes pas encore inscrit ?</a></p>

<form id="form_connexion-eleve" method="post" action="">

<?php
echo $this->Form_inputLabelBr('email', 'Votre adresse mail',
	array(
		'type'=>'email',
		'placeholder'=>'nom@fai.fr',
	));
echo $this->Form_inputLabelBr('password', 'Votre mot de passe',
	array(
		'type'=>'password',
	));
echo $this->Form_submit('connexion-eleve',"Connexion");
?>
</form>

<p class="see-link"><a href="/eleve/recuperation">Mot de passe perdu ?</a></p>