<h1>Accueil élève</h1>
<p class="intro">Bienvenue <?php echo $_SESSION['Eleve']->Mail ?> ! Cette page offre un récapitulatif de votre compte : vos derniers exercices, votre compte... ainsi, bien sûr, que la possibilité de créer un nouvel exercice.</p>

<h2>Créer un nouvel exercice</h2>
<a href="/eleve/exercice/creation">Créer un nouvel exercice</a>

<?php 
echo $this->View_render($this->Exo, 1);
?>