<?php 
if($this->getController()->getMembre()->Statut == 'BLOQUE')
{
	echo '<p class="important">Votre compte est bloqué. Certaines actions vous seront inaccessibles.</p>';
}
?>

<h2 id="eleve-exercice-index-creation">Créer un nouvel exercice</h2>

<p>Depuis cette section, vous pouvez créer un nouvel exercice et le soumettre à notre équipe qui se chargera d'y répondre dans vos délais.</p>
<a href="/eleve/exercice/creation" class="a_creation-exercice">Créer un nouvel exercice</a>

<?php 
echo $this->View_render($this->Exo);
echo $this->View_render($this->Points);
?>