<?php 
echo $this->Doc_box('eleve', 'inscription', 'Besoin d\'aide pour compléter ce formulaire ?');
?>
<form id="form_inscription-eleve" method="post" action="">

<?php
echo $this->Form_inputLabelBr(
	'email',
	'Votre adresse mail',
	array(
		'type' => 'email',
		'placeholder' => 'nom@domaine.fr',
		'required' => 'required',
	)
);
echo $this->Form_inputLabelBr(
	'password',
	'Votre mot de passe',
	array(
		'type' => 'password',
		'required' => 'required',
	)
);
echo $this->Form_inputLabelBr(
	'password_confirm',
	'Confirmez votre mot de passe',
	array(
		'type' => 'password',
		'required' => 'required',
	)
);
	
echo $this->Form_selectLabelBr(
	'classe',
	'Votre niveau scolaire',
	$this->Classes,
	2
);

echo $this->Form_inputLabelBr(
	'section',
	'Section (si nécessaire)',
	array(
		'placeholder' => 'S, ES, L...'
	)
);
?>

CGU Élèves<br />

<?php 
echo $this->Form_checkbox(
	'cgu',
	"J'ai lu et j'accepte les Conditions Générales d'Utilisation du site",
	false,
	array(
		'required' => 'required'
	)	
);
echo $this->Form_captcha();

echo $this->Form_submit('inscription-eleve', "M'inscrire");
?>
</form>