<form method="post" action="" id="form_edition-compte">
<?php
echo $this->Form_inputLabelBr(
	'email',
	'Votre adresse mail',
	array(
		'type'=>'email',
		'placeholder'=>'nom@fai.fr',
		'value' => $_SESSION['Eleve']->Mail
	)
);

echo $this->Form_inputLabelBr(
	'password',
	'Votre mot de passe (laissez vide pour conserver le mot de passe actuel)',
	array(
		'type'=>'password',
	)
);
echo $this->Form_inputLabelBr(
	'password_confirm',
	'Confirmez votre mot de passe',
	array(
		'type'=>'password',
	)
);

echo $this->Form_selectLabelBr(
	'classe',
	'Votre niveau scolaire',
	$this->Classes,
	$_SESSION['Eleve']->Classe
);

echo $this->Form_inputLabelBr(
	'section',
	'Section (si nécessaire)',
	array(
		'placeholder' => 'S, ES, L...',
		'value' => $_SESSION['Eleve']->Section
	)
);

echo $this->Form_submit('edition-compte', "Modifier les informations");
?>
</form>