<form method="post" action="" id="form_edition-compte">
<p class="infos">Avant de pouvoir modifier votre compte, veuillez marquer votre mot de passe.</p>
<?php
echo $this->Form_inputLabelBr(
	'password',
	'Votre mot de passe actuel',
	array(
		'type' => 'password',
		'required' => 'required'
	)
);
?>

<p>Modifiez ici vos informations, puis cliquer sur le bouton d'envoi.</p>

<?php
echo $this->Form_inputLabelBr(
	'email',
	'Votre adresse mail',
	array(
		'type' => 'email',
		'placeholder' => 'nom@domaine.fr',
		'value' => $_SESSION['Eleve']->Mail,
		'required' => 'required'
	)
);

echo $this->Form_inputLabelBr(
	'new-password',
	'Votre mot de passe (laissez vide pour conserver le mot de passe actuel)',
	array(
		'type' => 'password',
	)
);
echo $this->Form_inputLabelBr(
	'new-password-confirm',
	'Confirmez votre mot de passe',
	array(
		'type' => 'password',
	)
);

echo $this->Form_selectLabelBr(
	'classe',
	'Votre niveau scolaire',
	$this->Classes,
	$_SESSION['Eleve']->Classe
);

echo $this->Form_inputLabelBr(
	'section',
	'Section (si nécessaire)',
	array(
		'placeholder' => 'S, ES, L...',
		'value' => $_SESSION['Eleve']->Section
	)
);

echo $this->Form_submit('edition-compte', "Modifier les informations");
?>
</form>