<?php 
if(isset($this->Actions))
{
	echo $this->Html_list($this->Actions);
}
elseif(URL != PROD)
{
	?>
	<form id="form_clean-all" action="" method="post">
		<?php 
		echo $this->Form_inputLabelBr(
			'root-pw',
			'Mot de passe root',
			array(
				'type' => 'password',
				'required' => 'required',
				'autofocus' => 'autofocus'
			)
		);
		echo $this->Form_submit('clean-all', 'Attention ! Ràz globale !'); 
		?>
	</form>
	<p>Une fois ce bouton pressé, la suppression aura lieu. Elle peut prendre du temps, pas besoin de recliquer.</p>
	<?php 
}
else
{
	exit('On ne joue pas à ça en prod crétin !');
}?>