<?php 
echo $this->Date_countdownFull(time()+5) . '<br />';
echo $this->Date_countdownFull(time()+70) . '<br />';
echo $this->Date_countdownFull(time()+180) . '<br />';
echo $this->Date_countdownFull(time()+3550) . '<br />';
echo $this->Date_countdownFull(time()+(2*3600)) . '<br />';
echo $this->Date_countdownFull(time()+(24*2*3600)) . '<br />';
echo $this->Date_countdownFull(time()+(24*28*3600) - 10) . '<br />';
echo $this->Date_countdownFull(time()+(24*35*3600) - 10) . '<br />';
echo $this->Date_countdownFull(time()+(24*80*3600)) . '<br />';
?>