<h2 class="h2_logs" id="administrateur-log-eleve-derniers">Derniers élèves inscrits</h2>
<?php 
echo $this->Html_ajaxTable('/administrateur/log/_eleve', 'Derniers inscrits', array('Date', 'Mail', 'Statut', 'Classe', 'Lien'));
?>

<h2 class="h2_logs" id="administrateur-log-eleve-actions">Dernières actions élèves</h2>
<?php 
echo $this->Html_ajaxTable('/administrateur/log/_eleve_log', 'Dernières actions', array('Date', 'Mail', 'Action', '&Delta;', 'Lien'));
?>