<h2 class="h2_logs" id="administrateur-log-exercice-exercices">Derniers exercices</h2>
<?php 
echo $this->Html_ajaxTable('/administrateur/log/_exercice', 'Derniers exercices', array('Date', 'Exercice', 'Expiration', 'Lien'));
?>

<h2 class="h2_logs" id="administrateur-log-exercice-actions">Dernières actions</h2>
<?php 
echo $this->Html_ajaxTable('/administrateur/log/_exercice_log', 'Dernières actions', array('Date', 'Exercice', 'Action', 'Lien'));
?>