<div class="documentation-content">
<?php 
if(isset($this->MessageEnvoye))
{
	?>
	<p>Merci pour votre message !<br />
	<a href="/">Retourner à l'accueil <?php echo $this->Html_eDevoir(); ?></a>.</p>
	<?php
}
else
{
?>
<p>Vous souhaitez nous contacter ? Pas de problème.<br />
Merci d'entrer votre mail suivi de votre message dans ce formulaire.</p>

<form id="form_contact" method="post" action="">
<?php
echo $this->Form_inputLabelBr(
	'mail',
	'Votre adresse mail',
	array(
		'type' => 'email',
		'placeholder' => 'nom@domaine.fr'
	)
);

$Valeurs = $this->Valeurs;
echo $this->Form_selectLabelBr(
	'categorie',
	'Pourquoi souhaitez-vous nous contacter',
	array_combine($Valeurs, $Valeurs)
);

echo $this->Form_inputLabelBr('sujet', 'Sujet');

echo $this->Form_textareaLabelBr('message', 'Votre message (texte brut)');

echo $this->Form_captcha();

echo $this->Form_submit('contact', 'Envoyer mon message');
?>
</form>
<?php 
} //Fin if(isset($_POST['form_contact']))?>
</div>