<p>Vous souhaitez nous contacter ? Pas de problème.<br />
Merci d'entrer votre mail suivi de votre message dans ce formulaire.</p>

<form id="form_contact" method="post" action="">
<?php
echo $this->Form_inputLabelBr(
	'mail',
	'Votre adresse mail',
	array(
		'type' => 'email'
	)
);

$Valeurs = array('Question', 'Éclaircissement', 'Problème technique', 'Réclamation', 'Justification');
echo $this->Form_selectLabelBr(
	'categorie',
	'Pourquoi souhaitez-vous nous contacter',
	array_combine($Valeurs, $Valeurs)
);

echo $this->Form_inputLabelBr('sujet', 'Sujet');

echo $this->Form_textareaLabelBr('message', 'Votre message (texte brut)');

//TODO : captcha
echo $this->Form_submit('contact','Envoyer mon message');
?>