<p>Vous trouverez dans ces pages toute les informations nécessaires à l'utilisation d'<?php echo $this->Html_eDevoir(); ?>.</p>

<?php 
$Liste = array();
foreach($this->Pages as $Module=>$Pages)
{
	$Liste[] = '<li class="documentation-module-' . $Module . '">' . $Pages['index'] . $this->Html_listAnchor(
		$Pages,
		'ul',
		'/documentation/' . $Module . '/'
	) . '</li>';
}

echo '<ul class="documentation-module">';
echo implode("\n	", $Liste);
echo '</ul>';
?>