eDevoir vous permet de demander des corrections dans les matières suivantes :

    * Mathématiques
    * Physique
    * Chimie
    * Sciences de la Vie et de la Terre
    * Sciences de l’ingénieur
    * Français
    * Philosophie
    * Histoire
    * Géographie
    * Éducation civique, juridique et sociale
    * Anglais
    * Allemand
    * Espagnol
    * Italien
    * Autre langue vivante
    * Latin
    * Grec
    * Sciences économiques et sociales
    * Médecine
    * Informatique
    * Droit
    * PROJETS, RAPPORTS etc.