<div class="documentation-content">
<p><?php echo $this->Html_eDevoir(); ?> vous permet de demander des corrections pour les niveaux suivants :</p>

<?php 
echo $this->Html_list($this->Classes);
?>

<p>Lors de l'ajout d'un exercice (ou de l'inscription), vous pouvez indiquer votre section si nécessaire : par exemple "Technologique", "S" afin d'aider les correcteurs à s'adapter à vos besoins et connaissances.</p>
</div>