eDevoir vous permet de demander des corrections pour les niveaux suivants :

    * Sixième
    * Cinquième
    * Quatrième
    * Troisième
    * Seconde
    * Première
    * Terminale
    * Post-bac


Lors de l'ajout d'un exercice (ou de l'inscription), vous pouvez indiquer votre section si nécessaire : par exemple -- Seconde Technologique, Première S -- afin d'aider les correcteurs à s'adapter à vos besoins et connaissances.