<h1><?php echo $this->getMeta('title'); ?></h1>

<strong>eDevoir</strong> vous permet de demander des corrections pour les niveaux suivants :

<?php 
echo $this->Html_list($this->Classes);
?>

Lors de l'ajout d'un exercice (ou de l'inscription), vous pouvez indiquer votre section si nécessaire : par exemple « Technologique », « S » afin d'aider les correcteurs à s'adapter à vos besoins et connaissances.